version: 2.1

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/buildpack-deps:stretch
      environment:
        TZ: /usr/share/zoneinfo/Asia/Tokyo

jobs:
  build:
    <<: *defaults
    steps:
      - run:
          command: |
            cd Release
            make

workflows:
  workflows:
    jobs:
      - build

